spring.application.name=HospitalMangement

spring.datasource.url = jdbc:postgresql://localhost:5432/hospitaldb
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


spring.security.user.name=Tyagi
spring.security.user.password=g@123

